services:
  app:
    build: .
    container_name: doughnation
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma generate && npm run dev"
    volumes:
      - .:/app
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    container_name: postgres-doughnation
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doughnation
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
